TRAIN_IMAGES_DIR = "../data/TRAIN/HAZY"
TRAIN_LABELS_DIR = "../data/TRAIN/GT"
TEST_IMAGES_DIR = "../data/TEST/HAZY"
TEST_LABELS_DIR = "../data/TEST/GT"
VAL_IMAGES_DIR = "../data/VAL/HAZY"
VAL_LABELS_DIR = "../data/VAL/GT"
INFERENCE_DIR = "../inference"
WEIGHTS_DIR = "../weights"

INITIAL_LEARNING_RATE = 0.0001
IMAGE_SIZE = (512, 512)
COLOR_FORMAT = "YCrCb"
BATCH_SIZE = 8
EPOCHS = 400

DEVICE = "cuda:0"
NUM_WORKERS = 2
SHUFFLE = True
SEED = 42